export const ADD_PROJECT = "ADD_PROJECT";

export const GET_PROJECT_REQUEST = "GET_PROJECT_REQUEST";
export const GET_PROJECT_SUCCESS = "GET_PROJECT_SUCCESS";
export const GET_PROJECT_FAIL = "GET_PROJECT_FAIL";

export const GET_ALL_PROJECTS_REQUEST = "GET_ALL_PROJECTS_REQUEST";
export const GET_ALL_PROJECTS_SUCCESS = "GET_ALL_PROJECTS_SUCCESS";
export const GET_ALL_PROJECTS_FAIL = "GET_ALL_PROJECTS_FAIL";

export const GET_PROJECTS_FOR_OWNER_REQUEST = "GET_PROJECTS_FOR_OWNER_REQUEST";
export const GET_PROJECTS_FOR_OWNER_SUCCESS = "GET_PROJECTS_FOR_OWNER_SUCCESS";
export const GET_PROJECTS_FOR_OWNER_FAIL = "GET_PROJECTS_FOR_OWNER_FAIL";

export const CREATE_PROJECT_REQUEST = "CREATE_PROJECT_REQUEST";
export const CREATE_PROJECT_SUCCESS = "CREATE_PROJECT_SUCCESS";
export const CREATE_PROJECT_FAIL = "CREATE_PROJECT_FAIL";
